language: java

sudo: false

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
    - $HOME/.m2

env:
  matrix:
    - SUFFIX='-D spring.version=4.1.0.RELEASE'
    - SUFFIX='-D spring.version=4.2.0.RELEASE'
    - SUFFIX='-D spring.version=4.3.0.RELEASE'
    - SUFFIX=

script: ./mvnw clean verify $SUFFIX

after_success:
  - ./mvnw coveralls:report

notifications:
  email:
    on_failure: change
